# Generated by Django 4.2.7 on 2025-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguoidung',
            name='mat_khau',
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='password',
            field=models.CharField(db_column='Mat_khau', max_length=128),
        ),
    ]
